version: "3"

services:
  backend:
    build: ./python
    container_name: py-backend
    networks:
      br0:
        ipv4_address: "10.0.3.99"
    environment:
      - env
      - msg
      - IRC_TOKEN
      - API_ID
      - API_TOKEN
      - BOTNICK
      - CHANNELS
      - CLIENT_ID
      - CLIENT_SECRET
      - SUPABASE_URL
      - SUPABASE_API
      - TABLE
      - API_SERVER
      - WS_KEY
      - ABLY_KEY

networks:
  br0:
    external:
      name: br0
