version: '3'

services:
    web:
        build: ./api
        container_name: api-server
        ports:
            - "8000:8000"
        networks:
            sniffs.bot:
    backend:
        build: ./python
        container_name: py-backend
        networks:
            sniffs.bot:
        depends_on:
            - web
        environment:
            - env
            - msg
            - IRC_TOKEN
            - API_TOKEN
            - BOTNICK
            - CHANNELS
            - DB_HOST
            - DB_USER
            - DB_PASS
            - DB_NAME

networks:
    sniffs.bot: