version: "3"

services:
  backend:
    build: ./python
    container_name: py-backend
    networks:
      sniffs.bot:
    environment:
      - env
      - msg
      - IRC_TOKEN
      - API_ID
      - API_TOKEN
      - BOTNICK
      - CHANNELS
      - CLIENT_ID
      - CLIENT_SECRET
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASS
      - API_SERVER
      - WS_KEY

networks:
  sniffs.bot:
